blog/urls.py
from django.urls import path 
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('sing_up/', views.sing_up, name="singup"),
    path('singin/', views.iniciar_sesion, name="singin"),
    path('noticias/', views.noticias, name="noticias"),
    path('logout/', views.cerrar, name="logout"),
    

]  

dota/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('youtube', include('youtube.urls')),
    path('', include('foro.urls')),
    path('about', include('mensaje.urls')),


]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foro/urls.py
from . import views
from django.urls import path 


urlpatterns = [
    path('forum/', views.forum, name="forum"),
    path('crear_blog/', views.crear, name="crear"),

] 

mensaje/urls.py
from django.urls import path 
from . import views


urlpatterns = [
    path('', views.about, name="about"),
    

]

youtube/urls.py
from django.urls import path 
from . import views


urlpatterns = [
    path('', views.yout_ube, name="youtube"),
    

]

blog/models.py
from django.db import models

# Create your models here.
class Noticia(models.Model):
    titulo = models.TextField()
    descripcion = models.TextField()
    foto = models.ImageField(upload_to="youtube")
    enlace = models.URLField()
    subido = models.DateTimeField(auto_now=True)
    def __str__(self):
        return (self.titulo)

foro/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    titulo = models.TextField()
    usuario= models.ForeignKey(User,on_delete=models.CASCADE)
    descripcion = models.TextField()
    subido = models.DateTimeField(auto_now=True)
    foto = models.ImageField(upload_to="blog")
    def __str__(self):
        return (self.titulo)
    
class Comentarios(models.Model):
    comentarios = models.TextField()
    subido = models.DateTimeField(auto_now=True)
    relacion = models.ForeignKey(Post,on_delete=models.CASCADE,related_name="coments")
    def __str__(self):
        return (self.comentarios)

mensaje/models.py
from django.db import models

# Create your models here.

youtube/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class youtube(models.Model):
    titulo = models.TextField()
    descripcion = models.TextField()
    foto = models.ImageField(upload_to="youtube")
    enlace = models.URLField()
    subido = models.DateTimeField(auto_now=True)
    def __str__(self):
        return (self.titulo)

foro/forms.py
from django.forms import ModelForm
from .models import Post, Comentarios


class crearpost(ModelForm):
    class Meta:
        model = Post
        fields = ["titulo","descripcion","foto","usuario"]

class crearcomentario(ModelForm):
    class Meta:
          model = Comentarios
          fields = ["comentarios","relacion"]

blog/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from . models import Noticia
from youtube.models import youtube
from foro.models import Post
# Create your views here.
def index(request):
    newfoto = Noticia.objects.last()
    
    youfoto = youtube.objects.last()
    
    blogfoto = Post.objects.last()
    

    return render(request, "index.html",{"newfoto":newfoto,"youfoto":youfoto,"blogfoto":blogfoto})


    
def sing_up(request):
    if request.method == "GET" :
        return render(request, "sing_up.html", {"form": UserCreationForm })
    else:
        if request.POST["password1"] == request.POST["password2"]:
           try:
               user = User.objects.create_user(username=request.POST["username"], password=request.POST["password1"])
               user.save()
               login(request, user)
               return render(request, "index.html")
           except:
               return render(request,"sing_up.html",{"form": UserCreationForm,
                   "error": "Usuario ya existe"
               })
        else:
            return render(request,"sing_up.html",{"form": UserCreationForm,
                   "error": "Contraseña incorrecta"
               })

        
def cerrar(request):
    logout(request)
    return redirect("index")

def iniciar_sesion(request):

    if request.method == "GET":
        return render(request,"singin.html",{"form": AuthenticationForm})
    else:
       user = authenticate(request, username=request.POST["username"], password=request.POST["password"])
       if user is None:
           return render(request,"singin.html",{"form": AuthenticationForm, "error":"Username or password is incorrect"})
       else:
           login(request, user)
           return  redirect("index")
       
def noticias(request):
    form = Noticia.objects.all().order_by("-id")
    return render(request, "noticias.html",{"form":form})

foro/views.py
from django.shortcuts import render,redirect,HttpResponse
from . models import Post
from . forms import crearpost,crearcomentario
from django.contrib.auth.models import User

# Create your views here.

def forum(request):
    if request.method == "GET":
        post = Post.objects.all().order_by("-id")
        
        return render(request,"forum.html",{"post":post,"comentar":crearcomentario})
    else:
        
        comen = crearcomentario(request.POST)
        if comen.is_valid():
           comen.save()
           return redirect ("forum")
        else:
            return HttpResponse("Todos los campos son obligatorios, asegurese de incluir una foto")
  
def crear(request):
    if request.method == "GET":
        
        
        return render(request, "crear.html",{"form":crearpost})
    else:
        form = crearpost(request.POST, request.FILES)
        if form.is_valid():
           form.save()
           return redirect ("forum")
        else:
            return HttpResponse("Todos los campos son obligatorios, asegurese de incluir una foto")
        
    

mensaje/views.py
from django.shortcuts import render,HttpResponse
from django.conf import settings
from django.core.mail import send_mail

# Create your views here.
def about(request):
    if request.method == "GET":
        return render(request, "about.html")
    else:
        subject= request.POST["asunto"]
        messege = request.POST["mensaje"] + "" + request.POST["email"]
        email_from = settings.EMAIL_HOST_USER
        recipient_list = ["dota2.cuban@gmail.com"]
        send_mail(subject, messege, email_from, recipient_list)
        return HttpResponse("Mensaje enviado")

youtube/views.py
from django.shortcuts import render
from .models import youtube

# Create your views here.
def yout_ube(request):
    carta = youtube.objects.all().order_by("-id")
    return render(request, "youtube.html",{"carta":carta})

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dota Cuba</title>
    <meta name="description"content="pagina de dota 2 para los cubanos puedan compartir,interactuar">
    <meta name="author" content="HuNteR">
    <meta name="keywords"content="Dota2, Dota 2 Cuba, gaming, juegos en Cuba, Noticias en Cuba, páginas cubanas, cubanos en steam,Nauta Hogar, cubanos en dota">
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/styles.css' %}">
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
  

    <nav class="navbar navbar-expand-lg  bg-dark navbar-dark ">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Dota Cuba</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto" >
                <li class="nav-item">
                    <a  class="nav-link" href="/">Home</a>
                </li>
                
               
                <li class="nav-item">
                    <a class="nav-link" href="/noticias">Noticias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/forum">Forum</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/youtube">Youtube</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/about">Contáctenos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>



{% block content %}
{% endblock %}
<style>
  .social{
    margin: 50px 0;
    clear:both;
}
.social p{
    text-align: center;
    font-size: 30px;
    margin-bottom: 20px;
}

.link{
    display: flex;
    align-items: center;
    justify-content:center ;
}
.link a{
    margin: 0 30px;
}

.link a i{
    font-size: 3rem;
}

.fotterl{
   background:#2f3640 ;
   color: #616161; 
   font-size: 12px;
   padding: 35px 0;
}
.fotterc{
  display: grid; 
  justify-content: center;
}

.fotterc ul{
    margin: 0 auto;
}
.parrafoF{
  color: rgb(245, 241, 241); 
  text-align: center;

}


</style>
<section class="social">
  <p>Follow Dota 2 Cuba</p>
  <div class="link">
      <a href="https://facebook.com/groups/538402832968600/" >
          <i class="fab fa-facebook-f"></i>
      </a>
      <a href="https://chat.whatsapp.com/G2a4hjOVL449HjAmK0jeLF" ><i class="fab fa-whatsapp"></i>
      </a>
      <a href="https://t.me/DotaOnlineCuba" ><i class="fab fa-telegram"></i>
      </a>
  </div>
 </section>
  </div>
  <div class="fotterl">
      <div class="fotterc">
       <h3 class="parrafoF">DOTA 2 .CU by HuNteR</h3> 
      </div>

  </div>

blog/templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="card text-bg-dark">
    <img src="{% static 'blog/portada.jpg' %}" class="card-img" alt="...">
    <div class="card-img-overlay">
        {% if user.is_authenticated %}
        <div class="botondecerrar">
            <a class="btn btn-primary" href="/logout">Cerrar Cesión</a>
        </div>
        {% else %}
        
        
        <div class="botondecerrar">
            <a class="btn btn-primary" href="/singin/">
                Iniciar sesión
            </a>
             <a class="btn btn-primary" href="/sing_up/">
                 Crear cuenta
             </a>
        </div>
        
        {% endif %}
      <h5 class="card-title">Bienvenidos a la página cubana de Dota 2</h5>
      <p class="card-text">!!Hola gamers si disfrutan Dota2 tanto como yo, espero que entre todos creemos una gran comunidad!!</p>
      <p class="card-text"><small>Creada en 2024</small></p>
      <p class="card-text"><strong>Derechos reservados para HuNteR</strong></p>

    </div>
  </div>
<div>

</div>
  <div class="card-group">
    <div class="card">
      <img src="{% static 'blog/Noticias.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Noticias</h5>
        <p class="card-text">Mantente informado sobre todo lo que acontece en el mundo Gaming("Dota 2","Steam","Juegos Gratis","Ofertas especiales","Tarjetas de Regalo")</p>
        <a class="btn btn-primary" href="/noticias">Noticias</a>
      </div>
    </div>
    <div class="card">
      <img src="{% static 'blog/Forum.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Forum</h5>
        <p class="card-text">Mantente siempre en línea con la comunidad cubana</p>
        <a class="btn btn-primary" href="/forum">Forum</a>
      </div>
    </div>
    <div class="card">
      <img src="{% static 'blog/yotube.jpeg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Youtube</h5>
        <p class="card-text">Comparte junto a los desarrolladores de contenido</p>
        <a class="btn btn-primary" href="/youtube">Youtube</a>
      </div>
    </div>
  </div>


  <div id="carouselExampleCaptions" class="carousel slide">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{ newfoto.foto.url }}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5 class="card-text"><strong>{{newfoto.titulo}}</strong></h5>
          <a class="btn btn-primary" href="/noticias">Noticias</a>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{ youfoto.foto.url }}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5 class="card-text"><strong>{{youfoto.titulo}}</strong></h5>
          <a class="btn btn-primary" href="/youtube">Youtube</a>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{ blogfoto.foto.url }}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <p class="card-text"><strong>{{blogfoto.titulo}}</strong></p>
          <a class="btn btn-primary" href="/forum">Forum</a>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock %}

blog/templates/noticias.html
{% extends "base.html" %}
{% block content %}
<h1>Noticias</h1>

{% for form in form %}
<div class="card">
  <div class="card-body">
    <h1 class="card-title">{{form.titulo}}</h1>
    <h6 class="card-text">{{form.subido}}</h6>
    <p class="card-text">{{form.descripcion}}</p>
  </div>
  <img src="{{ form.foto.url }}" class="card-img-bottom" alt="...">
  <a href="{{form.enlace}}" class="btn btn-primary">Leer más</a>
</div>

{% endfor %}

{% endblock %}

blog/templates/sing_up.html
{% extends "base.html" %}
{% block content %}




<main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <form action="/sing_up/" method="post" class="card card-body">
                <h1 class="text-center">SingUp</h1>
                {{error}}
                 {% csrf_token %}
                <div class="mb-3">
                    <label for="username">Username:</label>
                    <input type="text"name="username" id="username"class="form-control"placeholder="Escribe tu nombre de usuario">
                </div>
                <div class="mb-3">
                    <label for="password1">Password:</label>
                    <input type="password"name="password1" id="password1"class="form-control"placeholder="Escribe tu contraseña">
                </div>
                <div class="mb-3">
                    <label for="password2">Confirm you password:</label>
                    <input type="password"name="password2" id="password2"class="form-control"placeholder="Confirma tu contraseña">
                </div>
                <button class="btn btn-primary">
                    SingUp
                </button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/singin.html
{% extends "base.html" %}
{% block content %}
<main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <form action="/singin/" method="post" class="card card-body">
                <h1 class="text-center">Singin</h1>
                {{error}}
                 {% csrf_token %}
                <div class="mb-3">
                    <label for="username">Username:</label>
                    <input type="text"name="username" id="username"class="form-control"placeholder="Escribe tu nombre de usuario">
                </div>
                <div class="mb-3">
                    <label for="password">Password:</label>
                    <input type="password"name="password" id="password"class="form-control"placeholder="Escribe tu contraseña">
                </div>
                <button class="btn btn-primary">
                    Iniciar Sesión
                </button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

foro/templates/crear.html
{% extends "base.html" %}
{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <form action="" method="post" class="card card-body" enctype="multipart/form-data">
                <h1 class="text-center">Crear Publicación</h1>
                {{error}}
                 {% csrf_token %}
                <div class="mb-3">
                    <label for="titulo">Título:</label>
                    <input type="text"name="titulo" id="titulo"class="form-control"placeholder="Escribe un título para tu publicación">
                </div>
                <div class="mb-3">
                    <label for="descripcion">Descripción:</label>
                    <input type="text"name="descripcion" id="descripcion"class="form-control"placeholder="Escribe una descripción">
                </div>
                <div class="mb-3">
                    <label for="foto">Foto</label>
                    <input type="file"name="foto" id="foto"class="form-control">
                </div>
                <div class="mb-3">
              
                    <select name="usuario" id="usuario">
                      <option value="{{user.id}}">{{user}}</option>
                    </select>
                  </div>
                <button class="btn btn-primary">
                    Subir
                </button>
            </form>
        </div>
    </div>
</main>

{% endblock %}



   

foro/templates/forum.html
{% extends "base.html" %}
{% block content %}




{% if user.is_authenticated %}

<div>
    <a class="btn btn-primary" href="/crear_blog">Crear Publicación</a>
</div>
{% else %}
<div>
    <p>Para publicar debes tener una cuenta </p>
    <a class="btn btn-primary" href="/">Crear cuenta</a>
</div>
{% endif %}
{% for post in post %}
       

  <div class="card">
      <div class="card-body">
        <h6 class="card-title">{{post.subido}}</h6>
        <h2 class="card-title">{{post.titulo}}:({{post.usuario}})</h2>
        <p class="card-text">{{post.descripcion}}</p>
      </div>
      <img src="{{ post.foto.url }}" class="card-img-bottom" alt="...">
    </div>
         
    <h6>Comentarios:</h6>
        {% for i in post.coments.all %}
            
          <p class="card-text">{{i.subido}}-{{i.comentarios}} </p>
             
        {% endfor %}
    
  {% if user.is_authenticated %}
   <div class="form-floating">
   <form action="" method="post" class="card card-body">
        <h1 class="text-center">Comentar</h1>
        {% csrf_token %}
          <div class="mb-3">
            <label for="comentarios">Comentario:</label>
            <input type="text"name="comentarios" id="comentarios"class="form-control"placeholder="Escribe un comentario">
            </div>
                <div class="mb-3">
              
                  <select name="relacion" id="id_relacion">
                    <option value="{{post.id}}">{{post.titulo}}</option>
                  </select>
                </div>
                <button class="btn btn-primary">
                    Comentar
                </button>
            </form>
    </div>
    {% endif %} 

  


 
{% endfor %}

{% endblock %}

mensaje/templates/about.html
{% extends "base.html" %}
{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <form action="" method="post" class="card card-body">
                <h1 class="text-center">Contáctenos</h1>
                
                 {% csrf_token %}
                <div class="mb-3">
                    <label for="asunto">Asunto:</label>
                    <input type="text"name="asunto" id="asunto"class="form-control"placeholder="Escribe el tema a tratar">
                </div>
                <div class="mb-3">
                    <label for="email">Email:</label>
                    <input type="text"name="email" id="email"class="form-control"placeholder="Escribe tu dirrección de correo">
                </div>
                <div class="mb-3">
                    <label for="mensaje">Mensaje:</label>
                    <input type="text"name="mensaje" id="mensaje"class="form-control"placeholder="Escribe un mensaje">
                </div>
                <button class="btn btn-primary">
                    Enviar
                </button>
            </form>
        </div>
    </div>
</main>

{% endblock %}

youtube/templates/youtube.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<style>
*{
    list-style: none;
	margin: 0;
	padding: 0;
	box-sizing: border-box;
}
    
    .you{
        background: #2f3640;
        color: white;
        border: 2px solid black;
        width: 40%;
        float:right;
        position:sticky;
        top: 20px;
        margin-top: 100px;
        
        
       
    }
    .you img{
        width: 50px;
        margin-top: 10px;
        margin-left: 30px;
        position:sticky;
        top: 20px;
    }
    .you a{
        color: white;
        margin-top: 10px;
        position:sticky;
        top: 20px;
        
    }
    .card{
        width: 60%;
        float:left;
    }
</style>
<div class="contenedorgeneral" >
    <aside>
        <div class="you">
            <ul>
                <li>
                    <img src="{% static 'youtube/wallace.png' %}" alt="">
                    <a class="btn btn-success" href="https://www.youtube.com/@W.Wallace-Dota">W. Wallace</a>
                </li>
                <li>
                    <img src="{% static 'youtube/qbandota.png' %}" alt="">
                    <a class="btn btn-success" href="https://www.youtube.com/@Qbandota322">Qban_dota</a>
                </li>
                <li>
                    <img src="{% static 'youtube/juanma.png' %}" alt="">
                    <a  class="btn btn-success" href="https://www.youtube.com/@JuanMaGonzalez1998">JuanMa Dota</a>
                </li>
            </ul>
        </div>
    </aside>
    {% for carta in carta %}
<div class="card mb-3">
    <img src="{{ carta.foto.url }}" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{carta.titulo}}</h5>
        <h6 class="card-text">{{carta.subido}}</h6>
        <p class="card-text">{{carta.descripcion}}</p>
        <a  class="btn btn-primary" href="{{carta.enlace}}">Visitar Canal</a>
    </div>
</div>

    {% endfor %}
</div>

        
        
        
 


{% endblock %}